<?xml version="1.0" encoding="utf-8"?><Database Name="Przepisy" Class="PrzepisyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Przepisy.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Inteligentna_Ksiazka_Kucharska.Properties.Settings" SettingsPropertyName="PrzepisyConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sklad" Member="Sklads">
    <Type Name="Sklad">
      <Column Name="sklad_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_przepisu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_produktu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ilosc" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Association Name="Przepisy_Sklad" Member="Przepisy" ThisKey="Id_przepisu" OtherKey="Id_przepisu" Type="Przepisy" IsForeignKey="true" />
      <Association Name="Produkt_Sklad" Member="Produkt" ThisKey="Id_produktu" OtherKey="Id_produktu" Type="Produkt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Przepisy" Member="Przepisies">
    <Type Name="Przepisy">
      <Column Name="Id_przepisu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Czas_przygotowania" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Instrukcje" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="Zdjecie" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Przepisy_Sklad" Member="Sklads" ThisKey="Id_przepisu" OtherKey="Id_przepisu" Type="Sklad" />
    </Type>
  </Table>
  <Table Name="dbo.ProduktLista" Member="ProduktListas">
    <Type Name="ProduktLista">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_produktu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lista_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Produkt_ProduktLista" Member="Produkt" ThisKey="Id_produktu" OtherKey="Id_produktu" Type="Produkt" IsForeignKey="true" />
      <Association Name="Lista_ProduktLista" Member="Lista" ThisKey="lista_ID" OtherKey="lista_ID" Type="Lista" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Produkt" Member="Produkts">
    <Type Name="Produkt">
      <Column Name="Id_produktu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Kalorie" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Białko" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Węglowodany" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Tłuszcze" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Produkt_Sklad" Member="Sklads" ThisKey="Id_produktu" OtherKey="Id_produktu" Type="Sklad" />
      <Association Name="Produkt_ProduktLista" Member="ProduktListas" ThisKey="Id_produktu" OtherKey="Id_produktu" Type="ProduktLista" />
    </Type>
  </Table>
  <Table Name="dbo.Lista" Member="Listas">
    <Type Name="Lista">
      <Column Name="lista_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Lista_ProduktLista" Member="ProduktListas" ThisKey="lista_ID" OtherKey="lista_ID" Type="ProduktLista" />
    </Type>
  </Table>
</Database>